import type { CourseInfo } from './types'

/**
 * Master list รายวิชา หลักสูตร วท.บ. วิทยาการคอมพิวเตอร์ (Computer Science) ปรับปรุง พ.ศ. 2569
 * (รวม 125 นก; วิชา GE ใช้กรอบ GE2565 ร่วมกับสถิติ — อยู่ใน ge-catalog.ts)
 * รหัส 322-101 (แคลคูลัส 1) ใช้ร่วมกับ catalog สถิติได้ จึงไม่ซ้ำที่นี่
 */
export const COURSES_CS: Record<string, CourseInfo> = {
  // ── กลุ่มแกนด้านวิทยาศาสตร์ คณิตศาสตร์ และเทคโนโลยี (12) ──
  '315-101': { code: '315-101', name: 'วิทยาศาสตร์และเทคโนโลยีในโลกยุคดิจิทัล', nameEn: 'Science and Technology in the Digital Age', credits: 3 },
  '345-101': { code: '345-101', name: 'การแก้ปัญหาด้วยคอมพิวเตอร์', nameEn: 'Problem Solving with Computer', credits: 3 },
  '346-101': { code: '346-101', name: 'สถิติและการวิเคราะห์ข้อมูลเบื้องต้น', nameEn: 'Basic Statistics and Data Analysis', credits: 3 },

  // ── วิชาเอกบังคับ (56) ──
  '344-101': { code: '344-101', name: 'พื้นฐานวิทยาการคอมพิวเตอร์', nameEn: 'Fundamentals of Computer Science', credits: 2 },
  '344-111': { code: '344-111', name: 'พื้นฐานการเขียนโปรแกรมคอมพิวเตอร์', nameEn: 'Fundamentals of Computer Programming', credits: 3 },
  '344-141': { code: '344-141', name: 'การออกแบบประสบการณ์ผู้ใช้และส่วนติดต่อผู้ใช้', nameEn: 'UX/UI Design', credits: 2 },
  '344-181': { code: '344-181', name: 'จรรยาบรรณสำหรับเทคโนโลยีดิจิทัล', nameEn: 'Ethics for Digital Technology', credits: 1 },
  '344-182': { code: '344-182', name: 'ทักษะการสื่อสารทางเทคโนโลยี', nameEn: 'Communication Skill in Technology', credits: 1 },
  '344-201': { code: '344-201', name: 'คณิตศาสตร์สำหรับวิทยาการคอมพิวเตอร์', nameEn: 'Mathematics for Computer Science', credits: 3 },
  '344-211': { code: '344-211', name: 'โครงสร้างข้อมูล', nameEn: 'Data Structures', credits: 3 },
  '344-212': { code: '344-212', name: 'การโปรแกรมเชิงวัตถุเบื้องต้น', nameEn: 'Introduction to Object-Oriented Programming', credits: 3 },
  '344-213': { code: '344-213', name: 'การวิเคราะห์และออกแบบอัลกอริทึม', nameEn: 'Algorithm Analysis and Design', credits: 3 },
  '344-221': { code: '344-221', name: 'สถาปัตยกรรมและองค์ประกอบคอมพิวเตอร์', nameEn: 'Computer Architectures and Organization', credits: 2 },
  '344-222': { code: '344-222', name: 'ระบบปฏิบัติการ', nameEn: 'Operating Systems', credits: 2 },
  '344-231': { code: '344-231', name: 'การวิเคราะห์และออกแบบระบบสารสนเทศ', nameEn: 'Information Systems Analysis and Design', credits: 3 },
  '344-232': { code: '344-232', name: 'หลักการระบบฐานข้อมูล', nameEn: 'Principles of Database Systems', credits: 3 },
  '344-251': { code: '344-251', name: 'การสื่อสารข้อมูลและเครือข่าย', nameEn: 'Data Communications and Networking', credits: 3 },
  '344-281': { code: '344-281', name: 'การคิดและการสร้างสรรค์สำหรับออกแบบนวัตกรรม', nameEn: 'Thinking and Creativity for Innovation Design', credits: 1 },
  '344-301': { code: '344-301', name: 'พีชคณิตเชิงเส้น', nameEn: 'Linear Algebra', credits: 3 },
  '344-321': { code: '344-321', name: 'พื้นฐานทางความปลอดภัยคอมพิวเตอร์', nameEn: 'Fundamentals of Computer Security', credits: 2 },
  '344-341': { code: '344-341', name: 'วิศวกรรมซอฟต์แวร์', nameEn: 'Software Engineering', credits: 3 },
  '344-361': { code: '344-361', name: 'หลักการปัญญาประดิษฐ์', nameEn: 'Principles of Artificial Intelligence', credits: 3 },
  '344-391': { code: '344-391', name: 'สัมมนาทางวิทยาการคอมพิวเตอร์', nameEn: 'Seminar in Computer Science', credits: 1 },
  '344-491': { code: '344-491', name: 'โครงงานทางวิทยาการคอมพิวเตอร์', nameEn: 'Projects in Computer Science', credits: 3 },
  '344-492': { code: '344-492', name: 'สหกิจศึกษา', nameEn: 'Cooperative Education', credits: 6 },
  '344-494': { code: '344-494', name: 'เตรียมสหกิจศึกษา (ไม่นับหน่วยกิต, ต้องได้ S)', nameEn: 'Pre-cooperative Education', credits: 1 },

  // ── วิชาเอกเลือก ด้านที่ 1: การพัฒนาซอฟต์แวร์ ──
  '344-214': { code: '344-214', name: 'การพัฒนาฟรอนท์เอ็นแอปพลิเคชัน', nameEn: 'Frontend Application Development', credits: 3 },
  '344-215': { code: '344-215', name: 'เทคโนโลยีการบริการผ่านเว็บและการประยุกต์', nameEn: 'Web Service Technology and Applications', credits: 3 },
  '344-233': { code: '344-233', name: 'ระบบจัดการความรู้', nameEn: 'Knowledge Management Systems', credits: 3 },
  '344-234': { code: '344-234', name: 'ระบบสารสนเทศทางภูมิศาสตร์', nameEn: 'Geographic Information Systems', credits: 3 },
  '344-311': { code: '344-311', name: 'การพัฒนาโปรแกรมประยุกต์บนอุปกรณ์เคลื่อนที่', nameEn: 'Mobile Application Development', credits: 3 },
  '344-312': { code: '344-312', name: 'การเขียนโปรแกรมบนเครื่องควอนตัมเบื้องต้น', nameEn: 'Introduction to Quantum Programming', credits: 3 },
  '344-334': { code: '344-334', name: 'การบริหารและบำรุงรักษาฐานข้อมูล', nameEn: 'Database Administration and Maintenance', credits: 3 },
  '344-335': { code: '344-335', name: 'การปรับแต่งฐานข้อมูลให้มีประสิทธิภาพ', nameEn: 'Advanced Database Technology', credits: 3 },
  '344-336': { code: '344-336', name: 'ระบบสารสนเทศทางการบัญชี', nameEn: 'Accounting Information System', credits: 3 },
  '344-342': { code: '344-342', name: 'การวิเคราะห์และออกแบบเชิงวัตถุ', nameEn: 'Object-Oriented Analysis and Design', credits: 3 },
  '344-343': { code: '344-343', name: 'วิศวกรรมความต้องการซอฟต์แวร์', nameEn: 'Software Requirement Engineering', credits: 3 },
  '344-344': { code: '344-344', name: 'การจัดการโครงการซอฟต์แวร์', nameEn: 'Software Project Management', credits: 3 },
  '344-345': { code: '344-345', name: 'ชุดวิชาเครื่องมือและการจัดการกระบวนงานพัฒนาซอฟต์แวร์', nameEn: 'Module: Software Development Tools and Workflow Management', credits: 3 },
  '344-433': { code: '344-433', name: 'เทคโนโลยีฐานข้อมูลยุคถัดไป', nameEn: 'Next Generation Database Technologies', credits: 3 },
  '344-441': { code: '344-441', name: 'การทดสอบและประกันคุณภาพซอฟต์แวร์', nameEn: 'Software Testing and Quality Assurance', credits: 3 },
  '344-442': { code: '344-442', name: 'สถาปัตยกรรมและการออกแบบซอฟต์แวร์', nameEn: 'Software Architecture and Design', credits: 3 },
  '344-443': { code: '344-443', name: 'การพัฒนาและการให้บริการระบบ', nameEn: 'Development Operations', credits: 3 },

  // ── วิชาเอกเลือก ด้านที่ 2: เทคโนโลยีอินเทอร์เน็ตและความมั่นคงปลอดภัยทางไซเบอร์ ──
  '344-223': { code: '344-223', name: 'การประมวลผลแบบฝังตัว', nameEn: 'Embedded Computing Systems', credits: 3 },
  '344-224': { code: '344-224', name: 'การรักษาความปลอดภัยบนระบบเครือข่าย', nameEn: 'Computer Systems and Network Security', credits: 3 },
  '344-225': { code: '344-225', name: 'จริยธรรมและกฎหมายในระบบคอมพิวเตอร์', nameEn: 'Computer Ethics and Cyber Laws', credits: 3 },
  '344-252': { code: '344-252', name: 'โปรโตคอลเครือข่าย', nameEn: 'Network Protocols', credits: 3 },
  '344-322': { code: '344-322', name: 'อินเทอร์เน็ตของสรรพสิ่ง', nameEn: 'Internet of Things', credits: 3 },
  '344-323': { code: '344-323', name: 'นิติวิทยาศาสตร์ไซเบอร์', nameEn: 'Cyber Forensics', credits: 3 },
  '344-324': { code: '344-324', name: 'การตรวจสอบด้านความปลอดภัย', nameEn: 'Security Penetration Testing and Audit', credits: 3 },
  '344-351': { code: '344-351', name: 'เทคโนโลยีไร้สาย', nameEn: 'Wireless Technology', credits: 3 },
  '344-352': { code: '344-352', name: 'โปรโตคอลเครือข่ายขั้นสูง', nameEn: 'Advanced Network Protocols', credits: 3 },
  '344-401': { code: '344-401', name: 'วิทยาการเข้ารหัสลับและความปลอดภัย', nameEn: 'Cryptography and Security', credits: 3 },
  '344-421': { code: '344-421', name: 'การประมวลผลสมรรถนะสูง', nameEn: 'High-performance Computing', credits: 3 },
  '344-422': { code: '344-422', name: 'ระบบประมวลผลแบบกลุ่มเมฆ', nameEn: 'Cloud Computing Systems', credits: 3 },
  '344-423': { code: '344-423', name: 'การจัดการความปลอดภัยทางไซเบอร์', nameEn: 'Cybersecurity Management', credits: 3 },
  '344-451': { code: '344-451', name: 'การบริการจัดการเครือข่าย', nameEn: 'Network Administration', credits: 3 },

  // ── วิชาเอกเลือก ด้านที่ 3: ปัญญาประดิษฐ์และวิทยาการข้อมูล ──
  '344-161': { code: '344-161', name: 'การทำความเข้าใจข้อมูลและสร้างแบบจำลองธุรกิจ', nameEn: 'Data Understanding and Business Modeling', credits: 3 },
  '344-235': { code: '344-235', name: 'การเตรียมข้อมูลสำหรับวิทยาการข้อมูล', nameEn: 'Data Preparation for Data Science', credits: 3 },
  '344-236': { code: '344-236', name: 'พื้นฐานวิทยาการข้อมูลและการวิศวกรรมข้อมูล', nameEn: 'Fundamentals of Data Science and Data Engineering', credits: 3 },
  '344-237': { code: '344-237', name: 'การวิเคราะห์ข้อมูลและการนำเสนอข้อมูลเชิงภาพ', nameEn: 'Data Analytics and Visualization', credits: 3 },
  '344-331': { code: '344-331', name: 'การทำเหมืองข้อมูล', nameEn: 'Data Mining', credits: 3 },
  '344-332': { code: '344-332', name: 'ข้อมูลขนาดใหญ่', nameEn: 'Big Data', credits: 3 },
  '344-333': { code: '344-333', name: 'การวิเคราะห์ข้อมูลและการพยากรณ์เพื่อการตัดสินใจ', nameEn: 'Data Analysis and Forecasting for Decision Making', credits: 3 },
  '344-362': { code: '344-362', name: 'การเรียนรู้ของเครื่อง', nameEn: 'Machine Learning', credits: 3 },
  '344-363': { code: '344-363', name: 'การปฏิบัติการด้านการเรียนรู้ของเครื่อง', nameEn: 'Machine Learning Operations', credits: 3 },
  '344-364': { code: '344-364', name: 'การเรียนรู้เชิงลึก', nameEn: 'Deep Learning', credits: 3 },
  '344-365': { code: '344-365', name: 'การประมวลผลภาษาธรรมชาติ', nameEn: 'Natural Language Processing', credits: 3 },
  '344-366': { code: '344-366', name: 'การทำงานอัตโนมัติของหุ่นยนต์สำหรับวิทยาการข้อมูล', nameEn: 'Robot Process Automation for Data Science', credits: 3 },
  '344-371': { code: '344-371', name: 'พื้นฐานการประมวลผลภาพเชิงดิจิทัล', nameEn: 'Fundamentals of Digital Image Processing', credits: 3 },
  '344-372': { code: '344-372', name: 'การประมวลผลภาพเชิงดิจิทัลชั้นสูง', nameEn: 'Advanced Digital Image Processing', credits: 3 },
  '344-431': { code: '344-431', name: 'การวิเคราะห์ข้อมูลและสารสนเทศการแพทย์', nameEn: 'Medical Informatics and Analytics', credits: 3 },
  '344-432': { code: '344-432', name: 'การออกแบบสถาปัตยกรรมข้อมูลขนาดใหญ่', nameEn: 'Big Data Architectural Design', credits: 3 },
  '344-461': { code: '344-461', name: 'การรู้จำรูปแบบ', nameEn: 'Pattern Recognition', credits: 3 },
  '344-462': { code: '344-462', name: 'ปัญญาประดิษฐ์สำหรับคอมพิวเตอร์เกม', nameEn: 'Artificial Intelligence for Computer Games', credits: 3 },
  '344-463': { code: '344-463', name: 'วิทยาการหุ่นยนต์เบื้องต้น', nameEn: 'Introduction to Robotics', credits: 3 },
  '344-464': { code: '344-464', name: 'การเรียนรู้ของหุ่นยนต์', nameEn: 'Machine Learning for Robotics', credits: 3 },
  '344-465': { code: '344-465', name: 'ธุรกิจอัจฉริยะ', nameEn: 'Business Intelligence', credits: 3 },
  '344-466': { code: '344-466', name: 'โครงงานทางด้านการเรียนรู้ของเครื่อง', nameEn: 'Project in Machine Learning', credits: 3 },
  '344-471': { code: '344-471', name: 'คอมพิวเตอร์วิทัศน์และการประยุกต์', nameEn: 'Computer Vision and Applications', credits: 3 },

  // ── รายวิชาเลือกอื่น ๆ ──
  '344-493': { code: '344-493', name: 'การฝึกงานทางคอมพิวเตอร์', nameEn: 'Job Training in Computer', credits: 2 },
  '344-495': { code: '344-495', name: 'หัวข้อพิเศษทางวิทยาการคอมพิวเตอร์ 1', nameEn: 'Special Topics in Computer Science I', credits: 3 },
  '344-496': { code: '344-496', name: 'หัวข้อพิเศษทางวิทยาการคอมพิวเตอร์ 2', nameEn: 'Special Topics in Computer Science II', credits: 3 },
  '344-497': { code: '344-497', name: 'หัวข้อพิเศษทางวิทยาการคอมพิวเตอร์ 3', nameEn: 'Special Topics in Computer Science III', credits: 2 },
  '344-498': { code: '344-498', name: 'หัวข้อพิเศษทางวิทยาการคอมพิวเตอร์ 4', nameEn: 'Special Topics in Computer Science IV', credits: 2 },
}
