/**
 * แคตตาล็อกหมวดวิชาศึกษาทั่วไป (GE) กลาง ม.อ. หาดใหญ่ — ฉบับปรับปรุงตามเกณฑ์ 2565
 * อัปเดตล่าสุดจากโครงสร้างรายวิชา GE ทางการ (gened.psu.ac.th — รวมมติสภามหาวิทยาลัยถึงปี 2569)
 * ที่มา: research/ge-structure.txt | generate โดย research/gen_ge2.py
 * group: GE1 ภาษา, GE2A ตรรกะ/ตัวเลข, GE2B คิดเชิงระบบ, GE3 ผู้ประกอบการ,
 *        GE4 ดิจิทัล, GE5 สุขภาวะ, GE6 จิตสาธารณะ/ยั่งยืน, GE7 ปรับตัวพลวัตโลก, GE8 เลือก
 */
export type GeGroup = 'GE1' | 'GE2A' | 'GE2B' | 'GE3' | 'GE4' | 'GE5' | 'GE6' | 'GE7' | 'GE8'

export interface GeCourse {
  code: string
  name: string
  nameEn?: string
  credits: number
  group: GeGroup
  audit?: boolean
}

export const GE_CATALOG: GeCourse[] = [
  // GE1
  { code: "890-101G1", name: "สรรสาระภาษาอังกฤษ", nameEn: "Essential English", credits: 2, group: 'GE1', audit: true },
  { code: "890-102G1", name: "ภาษาอังกฤษในชีวิตประจำวัน", nameEn: "Everyday English", credits: 2, group: 'GE1' },
  { code: "890-103G1", name: "ภาษาอังกฤษพร้อมใช้", nameEn: "English on the Go", credits: 2, group: 'GE1' },
  { code: "890-104G1", name: "ภาษาอังกฤษยุคดิจิทัล", nameEn: "English in the Digital World", credits: 2, group: 'GE1' },
  { code: "890-105G1", name: "ภาษาอังกฤษเชิงวิชาการ", nameEn: "English for Academic Success", credits: 2, group: 'GE1' },
  { code: "142-006G1", name: "ภาษาอังกฤษเชิงวิชาการฟังและพูด", nameEn: "Academic English: Listening and Speaking", credits: 2, group: 'GE1' },
  { code: "142-007G1", name: "ภาษาอังกฤษเชิงวิชาการอ่านและเขียน", nameEn: "Academic English: Reading and Writing", credits: 2, group: 'GE1' },
  { code: "890-175G1", name: "ทักษะการฟังและการอ่านภาษาอังกฤษ", credits: 2, group: 'GE1' },
  { code: "890-176G1", name: "ทักษะการฟังและการอ่านภาษาอังกฤษ", credits: 2, group: 'GE1' },
  { code: "890-177G1", name: "ทักษะการฟังและการอ่านภาษาอังกฤษ", credits: 2, group: 'GE1' },
  { code: "895-175G1", name: "ศิลปะการสื่อสาร", nameEn: "Arts of Communication", credits: 2, group: 'GE1' },
  // GE2A
  { code: "895-211G2A", name: "การคิดกับพฤติกรรมพยากรณ์", nameEn: "Thinking and Behavioral Prediction", credits: 2, group: 'GE2A' },
  { code: "315-100G2A", name: "คำนวณศิลป์", nameEn: "The Art of Computing", credits: 2, group: 'GE2A' },
  { code: "322-100G2A", name: "รวยด้วยคณิตศาสตร์", nameEn: "Getting rich with mathematics", credits: 2, group: 'GE2A' },
  { code: "473-001G2A", name: "เงินทองต้องรอบรู้", nameEn: "Financial Literacy for a Better Life", credits: 2, group: 'GE2A' },
  { code: "473-002G2A", name: "การอ่านงบการเงินเพื่อ", credits: 2, group: 'GE2A' },
  { code: "142-010G2A", name: "คิดไปข้างหน้า", nameEn: "Organic Thinking", credits: 2, group: 'GE2A' },
  // GE2B
  { code: "895-221G2B", name: "การคิดกับการแก้ปัญหาเชิงระบบ", nameEn: "Thinking and Systematic Problem Solving", credits: 2, group: 'GE2B' },
  { code: "895-222G2B", name: "การคิดเชิงวิพากษ์", nameEn: "Critical Thinking", credits: 2, group: 'GE2B' },
  { code: "895-223G2B", name: "คิดสร้างสุข", nameEn: "Cultivating Happiness through Positivity", credits: 2, group: 'GE2B' },
  { code: "895-224G2B", name: "ตรรกะในชีวิตประจำวัน", nameEn: "Logic in Daily Life", credits: 2, group: 'GE2B' },
  { code: "895-225G2B", name: "เท่าทันสถานการณ์โลก", nameEn: "The World Today", credits: 2, group: 'GE2B' },
  { code: "315-202G2B", name: "การคิดกับการใช้เหตุผล", nameEn: "Thinking and Reasoning", credits: 2, group: 'GE2B' },
  { code: "200-108G2B", name: "โมบาและการพัฒนากลยุทธ์", nameEn: "MOBA and Strategy Development", credits: 2, group: 'GE2B' },
  { code: "142-009G2B", name: "การแก้ปัญหาแบบสร้างสรรค์", nameEn: "Creative Problem Solving", credits: 2, group: 'GE2B' },
  // GE3
  { code: "895-301G3", name: "ก้าวแรกสู่ความเป็นผู้ประกอบการ", nameEn: "First Steps to Entrepreneurship", credits: 2, group: 'GE3' },
  { code: "895-302G3", name: "จุดประกายความคิดผ่านแนวคิดผู้ประกอบการ", nameEn: "Activating Innovative Ideas through an Entrepreneurial Mindset", credits: 2, group: 'GE3' },
  { code: "460-001G3", name: "แนวคิดและทักษะความเป็นผู้ประกอบการ", nameEn: "Entrepreneurial Mindset and Skills", credits: 2, group: 'GE3' },
  { code: "142-026G3", name: "การเป็นผู้ประกอบการ", nameEn: "Entrepreneurship", credits: 2, group: 'GE3' },
  { code: "895-176G3", name: "กรอบความคิดผู้ประกอบการ", nameEn: "Entrepreneurial Mindset", credits: 2, group: 'GE3' },
  // GE4
  { code: "315-104G4", name: "รู้ทันเทคโนโลยีดิจิทัล", nameEn: "Digital Technology Literacy", credits: 2, group: 'GE4' },
  { code: "200-107G4", name: "การเชื่อมต่อสรรพสิ่งเพื่อชีวิตยุคดิจิทัล", nameEn: "Internet of Thing for Digital Life", credits: 2, group: 'GE4' },
  { code: "200-104G4", name: "รู้เท่าทันปัญญาประดิษฐ์", nameEn: "Artificial Intelligence Literacy", credits: 2, group: 'GE4' },
  { code: "142-008G4", name: "โลกแห่งอนาคต", nameEn: "The Future Earth", credits: 2, group: 'GE4' },
  { code: "142-027G4", name: "เทคโนโลยีเอไอและการรู้เท่าทัน", nameEn: "AI Technologies and Literacy", credits: 2, group: 'GE4' },
  { code: "B03-001G4", name: "รู้เท่าทันภัยคุกคามทางไซเบอร์", credits: 2, group: 'GE4' },
  { code: "345-103G4", name: "เทคโนโลยีดิจิทัลเพื่อชีวิตประจำวันและการเรียนรู้", nameEn: "Digital Technology for Everyday Life and Learning", credits: 2, group: 'GE4' },
  // GE5
  { code: "895-501G5", name: "สุนทรียศาสตร์แห่งชีวิต", nameEn: "Life Aesthetics", credits: 2, group: 'GE5' },
  { code: "895-502G5", name: "พัฒนาจิตกับการสื่อสารเพื่อเข้าใจชีวิตมนุษย์", nameEn: "Mental Training for Empathetic Communication and Understanding of Human Life", credits: 2, group: 'GE5' },
  { code: "895-503G5", name: "สุขภาวะในการทำงาน", nameEn: "Well-being at Work", credits: 2, group: 'GE5' },
  { code: "895-504G5", name: "ความหมายของชีวิต", nameEn: "Meaning of Life", credits: 2, group: 'GE5' },
  { code: "895-505G5", name: "ศาสตร์และศิลป์เพื่อส่งเสริมสุขภาวะองค์รวม", nameEn: "Science and Art for Holistic Health Promotion", credits: 2, group: 'GE5' },
  { code: "950-102G5", name: "การปรับตัวของคนยุคใหม่ในสังคมใหม่", nameEn: "Adaptation of the", credits: 2, group: 'GE5' },
  { code: "950-103G5", name: "24 บอดี&มายด์", nameEn: "24 body&mind", credits: 2, group: 'GE5' },
  { code: "388-100G5", name: "สุขภาวะเพื่อเพื่อนมนุษย์", nameEn: "Health for all", credits: 2, group: 'GE5' },
  { code: "670-111G5", name: "สุขภาพองค์รวม", nameEn: "Holistic Health", credits: 2, group: 'GE5' },
  { code: "001-131G5", name: "สุขภาวะกายและจิต", nameEn: "Healthy Body and Mind", credits: 2, group: 'GE5' },
  { code: "670-211G5", name: "ทักษะล้มแล้วลุกได้", nameEn: "Resilience skill", credits: 2, group: 'GE5' },
  { code: "142-022G5", name: "โลกสวย", nameEn: "Life is Beautiful", credits: 2, group: 'GE5' },
  // GE6
  { code: "895-601G6", name: "พลเมืองตื่นรู้เพื่อการพัฒนาที่ยั่งยืน", nameEn: "Active Citizens for Sustainable Development", credits: 2, group: 'GE6' },
  { code: "001-102G6", name: "เป้าหมายการพัฒนาที่ยั่งยืนและการรับผิดชอบ", credits: 2, group: 'GE6' },
  { code: "003-001G6", name: "ผู้นำจิตอาสาเพื่อการพัฒนาชุมชน", nameEn: "Volunteer Leader for Community", credits: 2, group: 'GE6' },
  { code: "142-025G6", name: "ประโยชน์เพื่อนมนุษย์", nameEn: "Benefits of Mankind", credits: 2, group: 'GE6' },
  { code: "895-177G6", name: "โลกที่ยั่งยืน", nameEn: "Sustainable World", credits: 2, group: 'GE6' },
  // GE7
  { code: "820-100G7", name: "รักษ์โลก รักษ์เรา", nameEn: "Save Earth Save Us", credits: 2, group: 'GE7' },
  { code: "820-200G7", name: "เมื่อทะเลปั่นป่วน", nameEn: "Disrupted Sea", credits: 2, group: 'GE7' },
  { code: "315-201G7", name: "ชีวิตแห่งอนาคต", nameEn: "Life in the Future", credits: 2, group: 'GE7' },
  { code: "315-204G7", name: "รักษ์ทะเล", nameEn: "Marine conservation", credits: 2, group: 'GE7' },
  { code: "895-701G7", name: "มนุษยชาติกับความไม่แน่นอน", nameEn: "Humanity and Uncertainties", credits: 2, group: 'GE7' },
  { code: "200-103G7", name: "ชีวิตยุคใหม่หัวใจสีเขียว", nameEn: "Modern Life For Green Love", credits: 2, group: 'GE7' },
  { code: "142-024G7", name: "ศิลปะการดำเนินชีวิต", nameEn: "Art of Living", credits: 2, group: 'GE7' },
  { code: "500-102G7", name: "ไขรหัสลับทรัพยากรธรรมชาติ", nameEn: "Decoding Natural Resources", credits: 2, group: 'GE7' },
  { code: "895-178G7", name: "มนุษยชาติกับสิ่งแวดล้อม", nameEn: "Humanity and Environment", credits: 2, group: 'GE7' },
  // GE8
  { code: "895-861G8", name: "กีตาร์", nameEn: "The Guitar", credits: 2, group: 'GE8' },
  { code: "895-862G8", name: "อูคูเลเล่", nameEn: "The Ukulele", credits: 2, group: 'GE8' },
  { code: "895-863G8", name: "ฮาร์โมนิกา", nameEn: "The Harmonica", credits: 2, group: 'GE8' },
  { code: "895-864G8", name: "ดนตรีตะวันตก", nameEn: "Western Music", credits: 2, group: 'GE8' },
  { code: "895-865G8", name: "ขิมไทย", nameEn: "The Traditional Thai Dulcimer", credits: 2, group: 'GE8' },
  { code: "895-866G8", name: "ดนตรีปี่พาทย์", nameEn: "Piphat Ensembles", credits: 2, group: 'GE8' },
  { code: "895-867G8", name: "ดนตรีพัฒนาความคิดสร้างสรรค์", nameEn: "Creative Music", credits: 2, group: 'GE8' },
  { code: "895-868G8", name: "ดนตรีอาเซียน", nameEn: "ASEAN Music", credits: 2, group: 'GE8' },
  { code: "895-833G8", name: "ดูหนังดูละครย้อนดูตน", nameEn: "Drama and Self-reflection", credits: 2, group: 'GE8' },
  { code: "895-834G8", name: "วาดเส้นสร้างสรรค์", nameEn: "Creative Drawing", credits: 2, group: 'GE8' },
  { code: "895-843G8", name: "อรรถรสภาษาไทย", nameEn: "Appreciation of the Thai Language", credits: 2, group: 'GE8' },
  { code: "315-102G8", name: "สุนทรียศาสตร์การถ่ายภาพ", nameEn: "The Aesthetic in Photography", credits: 2, group: 'GE8' },
  { code: "061-001G8", name: "ความงามของนาฎศิลป์ไทย", nameEn: "Aesthetics of Thai Dance", credits: 2, group: 'GE8' },
  { code: "061-002G8", name: "สุนทรียะดนตรีกับชีวิต", nameEn: "Music aesthetics in Life", credits: 2, group: 'GE8' },
  { code: "061-003G8", name: "โนราเพื่อสุขภาพ", nameEn: "Nora for health", credits: 2, group: 'GE8' },
  { code: "895-871G8", name: "เปตอง", nameEn: "Pétanque", credits: 2, group: 'GE8' },
  { code: "895-872G8", name: "ตะกร้อ", nameEn: "Takraw", credits: 2, group: 'GE8' },
  { code: "895-873G8", name: "ฟุตซอล", nameEn: "Futsal", credits: 2, group: 'GE8' },
  { code: "895-874G8", name: "ลีลาศ", nameEn: "Social Dance", credits: 2, group: 'GE8' },
  { code: "895-875G8", name: "แบดมินตัน", nameEn: "Badminton", credits: 2, group: 'GE8' },
  { code: "895-876G8", name: "ว่ายน้ำ", nameEn: "Swimming", credits: 2, group: 'GE8' },
  { code: "895-877G8", name: "ว่ายน้ำช่วยชีวิต", nameEn: "Swimming for Lifesaving", credits: 2, group: 'GE8' },
  { code: "895-878G8", name: "เทเบิลเทนนิส", nameEn: "Table Tennis", credits: 2, group: 'GE8' },
  { code: "895-879G8", name: "เทนนิส", nameEn: "Tennis", credits: 2, group: 'GE8' },
  { code: "895-880G8", name: "การออกกำลังกายเพื่อสุขภาพ", nameEn: "Exercise for Health", credits: 2, group: 'GE8' },
  { code: "895-881G8", name: "อ้วนได้ ผอมได้", nameEn: "Fat to Fit", credits: 2, group: 'GE8' },
  { code: "895-882G8", name: "ฟิต แอนด์ เฟิร์ม", nameEn: "Fit and Firm", credits: 2, group: 'GE8' },
  { code: "895-883G8", name: "ค่ายสร้างสุข", nameEn: "Happy Camping", credits: 2, group: 'GE8' },
  { code: "895-884G8", name: "บาสเกตบอล", nameEn: "Basketball", credits: 2, group: 'GE8' },
  { code: "895-885G8", name: "มวยไทย", nameEn: "Muay Thai", credits: 2, group: 'GE8' },
  { code: "895-886G8", name: "วอลเลย์บอล", nameEn: "Volleyball", credits: 2, group: 'GE8' },
  { code: "895-887G8", name: "ฟุตบอล", nameEn: "Football", credits: 2, group: 'GE8' },
  { code: "890-811G8", name: "ไวยากรณ์อังกฤษเพื่อการสื่อสารในชีวิตจริง", nameEn: "English Grammar for Real Life Communication", credits: 2, group: 'GE8' },
  { code: "890-821G8", name: "ฝึกสำเนียงผ่านเสียงเพลง", nameEn: "English Pronunciation through Songs", credits: 2, group: 'GE8' },
  { code: "890-831G8", name: "กลยุทธ์การอ่านภาษาอังกฤษอย่างเข้าใจ", nameEn: "Strategic Reading for Greater Comprehension", credits: 2, group: 'GE8' },
  { code: "890-841G8", name: "ภาษาอังกฤษเพื่อการนำเสนอและออกแบบสื่อ", nameEn: "English for Presentations and Visual Aids Design", credits: 2, group: 'GE8' },
  { code: "890-842G8", name: "การฟัง-พูดภาษาอังกฤษสำหรับพลเมืองยุคดิจิทัล", nameEn: "English Listening and Speaking for Digital Citizens", credits: 2, group: 'GE8' },
  { code: "890-843G8", name: "การสนทนาภาษาอังกฤษ", nameEn: "English Conversation", credits: 2, group: 'GE8' },
  { code: "890-851G8", name: "บูรณาการอ่านเขียนภาษาอังกฤษ", nameEn: "Reading to Write in English", credits: 2, group: 'GE8' },
  { code: "890-852G8", name: "การอ่านและการเขียนภาษาอังกฤษเชิงวิชาการ", nameEn: "Academic Reading and Writing in English", credits: 2, group: 'GE8' },
  { code: "890-861G8", name: "เรียนภาษาอังกฤษผ่านข่าว", nameEn: "Consolidating English through News", credits: 2, group: 'GE8' },
  { code: "890-862G8", name: "ภาษาอังกฤษตลอดเวลา", nameEn: "English around the Clock", credits: 2, group: 'GE8' },
  { code: "890-863G8", name: "ภาษาอังกฤษเพื่อการรู้เท่าทันสื่อดิจิทัล", nameEn: "English for Digital Literacy", credits: 2, group: 'GE8' },
  { code: "890-871G8", name: "การเขียนภาษาอังกฤษด้วยเทคโนโลยีออนไลน์", nameEn: "English Writing with Online Technology", credits: 2, group: 'GE8' },
  { code: "890-872G8", name: "ภาษาอังกฤษกับเครื่องมือดิจิทัล", nameEn: "English and Digital Tools", credits: 2, group: 'GE8' },
  { code: "890-873G8", name: "เรียนรู้ภาษาอังกฤษจากคลังข้อมูลออนไลน์", nameEn: "Discovering English with Online Corpora", credits: 2, group: 'GE8' },
  { code: "890-874G8", name: "แปลสิกูเกิล", nameEn: "Google Translate Me", credits: 2, group: 'GE8' },
  { code: "890-881G8", name: "ภาษาอังกฤษพิชิตการสมัครงาน", nameEn: "English for Job Applications", credits: 2, group: 'GE8' },
  { code: "890-882G8", name: "ภาษาอังกฤษในที่ทำงาน", nameEn: "English in the Workplace", credits: 2, group: 'GE8' },
  { code: "890-883G8", name: "ภาษาอังกฤษสำหรับนักท่องเที่ยว", nameEn: "English for Travelers", credits: 2, group: 'GE8' },
  { code: "890-884G8", name: "ภาษาอังกฤษสำหรับผู้ประกอบการและผู้บริโภค", nameEn: "English for Entrepreneurs and Consumers", credits: 2, group: 'GE8' },
  { code: "890-885G8", name: "กลยุทธ์พิชิตข้อสอบภาษาอังกฤษเพื่อการทำงาน", nameEn: "English Test Taking Strategies for Employment", credits: 2, group: 'GE8' },
  { code: "890-886G8", name: "การเรียนรู้ภาษาอังกฤษผ่านวัฒนธรรม", nameEn: "Learning English through Cultures", credits: 2, group: 'GE8' },
  { code: "891-811G8", name: "ก้าวแรกสู่ภาษาญี่ปุ่น", nameEn: "First Steps to Japanese", credits: 2, group: 'GE8' },
  { code: "891-812G8", name: "สนทนาภาษาญี่ปุ่นในชีวิตประจำวัน", nameEn: "Japanese Conversation in Daily Life", credits: 2, group: 'GE8' },
  { code: "891-813G8", name: "สนทนาภาษาญี่ปุ่นในที่ทำงาน", nameEn: "Japanese Conversation in the Workplace", credits: 2, group: 'GE8' },
  { code: "891-821G8", name: "ภาษาจีนเบื้องต้น", nameEn: "Basic Chinese", credits: 2, group: 'GE8' },
  { code: "891-822G8", name: "สนทนาภาษาจีนในชีวิตประจำวัน", nameEn: "Chinese Conversation in Daily Life", credits: 2, group: 'GE8' },
  { code: "891-823G8", name: "สนทนาภาษาจีนในที่ทำงาน", nameEn: "Chinese Conversation in the Workplace", credits: 2, group: 'GE8' },
  { code: "891-824G8", name: "ศิลปะการเขียนพู่กันจีน", nameEn: "Chinese Calligraphy", credits: 2, group: 'GE8' },
  { code: "891-831G8", name: "ภาษามลายูเบื้องต้น", nameEn: "Basic Malay", credits: 2, group: 'GE8' },
  { code: "891-832G8", name: "สนทนาภาษามลายูในชีวิตประจำวัน", nameEn: "Malay Conversation in Daily Life", credits: 2, group: 'GE8' },
  { code: "891-833G8", name: "สนทนาภาษามลายูสำหรับการท่องเที่ยว", nameEn: "Malay Conversation for Tourism", credits: 2, group: 'GE8' },
  { code: "891-841G8", name: "พูดได้ พูดดี ภาษาเกาหลีเบื้องต้น", nameEn: "Survival Korean for Thais", credits: 2, group: 'GE8' },
  { code: "891-842G8", name: "สนทนาภาษาเกาหลีสำหรับมือใหม่", nameEn: "Korean Conversation for Beginners", credits: 2, group: 'GE8' },
  { code: "891-843G8", name: "อินและฟินกับภาษาและวัฒนธรรมเกาหลี", nameEn: "Insights into Korean Language and Culture", credits: 2, group: 'GE8' },
  { code: "891-861G8", name: "ทำความรู้จักภาษาอินโดนีเซีย", nameEn: "Getting to Know Bahasa Indonesia", credits: 2, group: 'GE8' },
  { code: "891-862G8", name: "ภาษาอินโดนีเซียเพื่อการสื่อสารในชีวิตประจำวัน", nameEn: "Bahasa Indonesia for Everyday Communication", credits: 2, group: 'GE8' },
  { code: "891-863G8", name: "ภาษาอินโดนีเซียในที่ทำงาน", nameEn: "Bahasa Indonesia in the Workplace", credits: 2, group: 'GE8' },
  { code: "895-811G8", name: "จิตวิทยาความรัก", nameEn: "Psychology of Love", credits: 2, group: 'GE8' },
  { code: "895-812G8", name: "ชีวิตดี มีจิตวิทยา", nameEn: "Psychology for Good Life", credits: 2, group: 'GE8' },
  { code: "895-813G8", name: "เด็กใหม่ป้ายแดง", nameEn: "Workplace Newcomers", credits: 2, group: 'GE8' },
  { code: "895-814G8", name: "รู้เขา รู้เรา ผ่านพฤติกรรมมนุษย์", nameEn: "Knowing Others and Yourself through Human Behaviors", credits: 2, group: 'GE8' },
  { code: "895-815G8", name: "ปฏิสัมพันธ์ทางสังคม", nameEn: "Social Interaction", credits: 2, group: 'GE8' },
  { code: "895-816G8", name: "พัฒนศึกษา", nameEn: "Development Studies", credits: 2, group: 'GE8' },
  { code: "895-817G8", name: "เสน่ห์แห่งบุคลิกภาพ", nameEn: "Charming Personality", credits: 2, group: 'GE8' },
  { code: "895-818G8", name: "ทักษะชีวิตในสังคม 5.0", nameEn: "Life Skills in Society 5.0", credits: 2, group: 'GE8' },
  { code: "895-819G8", name: "เข้าใจตน เข้าใจคน", nameEn: "Me and Others", credits: 2, group: 'GE8' },
  { code: "895-821G8", name: "ความเชื่อกับการท่องเที่ยว", nameEn: "Tourism and Superstition", credits: 2, group: 'GE8' },
  { code: "895-822G8", name: "แบกเป้เที่ยว", nameEn: "Backpacking Trips", credits: 2, group: 'GE8' },
  { code: "895-823G8", name: "จิตวิทยาการบริการ", nameEn: "Psychology for Service", credits: 2, group: 'GE8' },
  { code: "895-824G8", name: "การท่องเที่ยวเชิงสร้างสรรค์", nameEn: "Creative Tourism", credits: 2, group: 'GE8' },
  { code: "895-825G8", name: "การท่องเที่ยวอย่างมีจิตสาธารณะ", nameEn: "Volunteer Tourism", credits: 2, group: 'GE8' },
  { code: "895-826G8", name: "ผู้โดยสารโปรดทราบ", nameEn: "Passengers Your attention Please", credits: 2, group: 'GE8' },
  { code: "895-827G8", name: "ตะลุยแดนมรดกโลกในอาเซียน", nameEn: "ASEAN World Heritage Sites", credits: 2, group: 'GE8' },
  { code: "895-831G8", name: "จริยศาสตร์แห่งชีวิต", nameEn: "Ethics for Life", credits: 2, group: 'GE8' },
  { code: "895-832G8", name: "นานาศาสนา", nameEn: "Religious Diversity", credits: 2, group: 'GE8' },
  { code: "895-835G8", name: "ศิลปะในสังคมพหุวัฒนธรรม", nameEn: "Art in Multicultural Society", credits: 2, group: 'GE8' },
  { code: "895-836G8", name: "จีน: อดีต ปัจจุบัน อนาคต", nameEn: "China : Past, Present, and Future", credits: 2, group: 'GE8' },
  { code: "895-837G8", name: "โหราศาสตร์กับการดำเนินชีวิต", nameEn: "Astrology and Life", credits: 2, group: 'GE8' },
  { code: "895-838G8", name: "ประวัติศาสตร์ในภาพยนตร์", nameEn: "History in Movies", credits: 2, group: 'GE8' },
  { code: "895-841G8", name: "ทักษะการสื่อสาร", nameEn: "Communication Skills", credits: 2, group: 'GE8' },
  { code: "895-842G8", name: "ทักษะการฟังและการพูดภาษาไทย", nameEn: "Thai Listening and Speaking Skills", credits: 2, group: 'GE8' },
  { code: "895-844G8", name: "ศิลปะการเขียนเชิงสร้างสรรค์", nameEn: "The Art of Creative Writing", credits: 2, group: 'GE8' },
  { code: "895-845G8", name: "วรรณกรรมอาเซียน", nameEn: "ASEAN Literature", credits: 2, group: 'GE8' },
  { code: "895-846G8", name: "มนุษย์กับวรรณกรรม", nameEn: "Man and Literature", credits: 2, group: 'GE8' },
  { code: "895-847G8", name: "วัฒนธรรมในวรรณกรรม", nameEn: "Culture in Literature", credits: 2, group: 'GE8' },
  { code: "895-848G8", name: "ภาษาและวัฒนธรรมไทย", nameEn: "Thai Language and Culture", credits: 2, group: 'GE8' },
  { code: "895-849G8", name: "ศิลปะการฟัง", nameEn: "The Art of Listening", credits: 2, group: 'GE8' },
  { code: "895-850G8", name: "การใช้ภาษาไทย", nameEn: "Thai Usage", credits: 2, group: 'GE8' },
  { code: "895-851G8", name: "เสน่ห์ภาษาไทยถิ่นใต้", nameEn: "The Charm of Southern Thai Dialects", credits: 2, group: 'GE8' },
  { code: "315-103G8", name: "ความรู้ทั่วไปทางด้านทรัพย์สินทางปัญญา", nameEn: "Introduction to Intellectual Property", credits: 2, group: 'GE8' },
  { code: "336-214G8", name: "กินดี ชีวิตดี", nameEn: "Smart Eating and Being Healthy", credits: 2, group: 'GE8' },
  { code: "336-215G8", name: "ชีวิตปลอดภัยจากสารพิษ", nameEn: "Safety Life from Toxic Substances", credits: 2, group: 'GE8' },
  { code: "336-216G8", name: "ยาและสุขภาพ", nameEn: "Drug and Health", credits: 2, group: 'GE8' },
  { code: "315-203G8", name: "กุญแจไขธรรมชาติ", nameEn: "Key to Nature", credits: 2, group: 'GE8' },
  { code: "315-205G8", name: "วิทย์คิดรวย", nameEn: "Science Entrepreneur Pitching", credits: 2, group: 'GE8' },
  { code: "315-206G8", name: "ไขความจริงทุกสรรพสิ่ง", nameEn: "Science Facts", credits: 2, group: 'GE8' },
  { code: "338-101G8", name: "เรื่องของฉัน", nameEn: "My body and health", credits: 2, group: 'GE8' },
  { code: "874-191G8", name: "ความรู้พื้นฐานเกี่ยวกับระบบกฎหมายไทย", nameEn: "Introduction to Thai Legal System", credits: 2, group: 'GE8' },
  { code: "874-192G8", name: "กฎหมายเพื่อการประกอบอาชีพ", credits: 2, group: 'GE8' },
  { code: "874-193G8", name: "ความรู้เบื้องต้นเกี่ยวกับกฎหมายและกระบวนการยุติธรรม", nameEn: "General Principles of Law and Judicial Process", credits: 2, group: 'GE8' },
  { code: "874-194G8", name: "ภาษีอากรกับชีวิต", nameEn: "Taxation and Life", credits: 2, group: 'GE8' },
  { code: "874-195G8", name: "สิทธิมนุษยชนกับความเป็นพลเมือง", nameEn: "Human Rights and Citizenship", credits: 2, group: 'GE8' },
  { code: "193-031G8", name: "ธรรมชาติบำบัด", nameEn: "Natural Therapy", credits: 2, group: 'GE8' },
  { code: "003-002G8", name: "ม.อ.เพื่อเพื่อนมนุษย์", nameEn: "PSU FOR MANKIND", credits: 2, group: 'GE8' },
  { code: "001-101G8", name: "อาเซียนศึกษา", nameEn: "ASEAN Studies", credits: 2, group: 'GE8' },
  { code: "858-154G8", name: "บรรจุภัณฑ์รักษ์สิ่งแวดล้อมในชีวิตประจำวัน", nameEn: "Green packaging in daily life", credits: 2, group: 'GE8' },
  { code: "858-161G8", name: "โภชนาการและอาหารสุขภาพในชีวิตประจำวัน", nameEn: "Nutrition and Healthy Food in Daily Life", credits: 2, group: 'GE8' },
  { code: "858-162G8", name: "เลือกซื้อ เลือกกิน อย่างชาญฉลาด", nameEn: "Being a Smart Consumer", credits: 2, group: 'GE8' },
  { code: "670-411G8", name: "ลิขิตชีวิตตน", nameEn: "Leading your life", credits: 2, group: 'GE8' },
  { code: "500-101G8", name: "ฟาร์มสุข", nameEn: "Happy farm", credits: 2, group: 'GE8' },
  { code: "200-105G8", name: "สมาธิเพื่อพัฒนาชีวิต", nameEn: "Meditation for Life Development", credits: 2, group: 'GE8' },
  { code: "895-891G8", name: "จิตวิทยาอุตสาหกรรมกับการทำงานยุควิถีใหม่", nameEn: "Industrial Psychology in the New Normal of Work", credits: 2, group: 'GE8' },
  { code: "895-892G8", name: "กินสร้างสุข", nameEn: "Eat Right for a Happy Life", credits: 2, group: 'GE8' },
  { code: "142-001G8", name: "ยกเครื่องเรื่องอังกฤษ", nameEn: "English Booster", credits: 2, group: 'GE8' },
  { code: "142-002G8", name: "อังกฤษออนแอร์", nameEn: "English On Air", credits: 2, group: 'GE8' },
  { code: "142-003G8", name: "ภาษาอังกฤษสำหรับพื้นฐานเทคโนโลยี", credits: 2, group: 'GE8' },
  { code: "142-004G8", name: "อังกฤษจริตจะก้าน", nameEn: "English Pronunciation", credits: 2, group: 'GE8' },
  { code: "142-005G8", name: "การเขียนขั้นเทพ", nameEn: "Advanced Writing", credits: 2, group: 'GE8' },
  { code: "142-011G8", name: "ใคร ๆ ก็วาดได้", nameEn: "Everyone Can Draw", credits: 2, group: 'GE8' },
  { code: "142-012G8", name: "มนต์รักเสียงดนตรี", nameEn: "The Sound of Music", credits: 2, group: 'GE8' },
  { code: "142-013G8", name: "อังกฤษกันทุกวัน", nameEn: "Everyday English", credits: 2, group: 'GE8' },
  { code: "142-014G8", name: "ภาษาอังกฤษเพื่อการพัฒนาปัจเจก", credits: 2, group: 'GE8' },
  { code: "142-015G8", name: "ภาษาสื่อและศิลปะการเล่าเรื่อง", nameEn: "Media Language and Art of Storytelling", credits: 2, group: 'GE8' },
  { code: "142-016G8", name: "การพูดในที่สาธารณะ", nameEn: "Public Speaking", credits: 2, group: 'GE8' },
  { code: "142-017G8", name: "สื่อสร้างสรรค์สำหรับการนำเสนอผลงาน", credits: 2, group: 'GE8' },
  { code: "142-018G8", name: "ปัจจัยที่ 5", nameEn: "The 5th need", credits: 2, group: 'GE8' },
  { code: "142-019G8", name: "การตลาดบนยูทูป", nameEn: "Youtube Marketing", credits: 2, group: 'GE8' },
  { code: "142-020G8", name: "การออกแบบกระบวนการคิดและ", credits: 2, group: 'GE8' },
  { code: "142-021G8", name: "การจัดการสื่อโฆษณาออนไลน์", nameEn: "Online Advertising Management", credits: 2, group: 'GE8' },
  { code: "142-023G8", name: "ตะลอนทัวร์", nameEn: "Learn to Roam", credits: 2, group: 'GE8' },
  // วิชา GE รหัสเก่าที่ยังพบใน transcript (นับเป็น GE8 เลือก)
  { code: '145-101', name: 'สัตว์เลี้ยงเพื่อนรัก', nameEn: 'Companion Animals', credits: 3, group: 'GE8' },
]

export const GE_BY_CODE: Record<string, GeCourse> = Object.fromEntries(
  GE_CATALOG.map((c) => [c.code, c]),
)
